#!/bin/sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sh $HOME/.scripts/kblayout.sh &
sh $HOME/.scripts/keyrate.sh &
xrdb $HOME/.Xresources &
dunst &
pulseaudio &
mpd &
numlockx on &
picom --experimental-backends -b &
sh $HOME/.scripts/defaultdisplay.sh &
sh $HOME/.scripts/defaultwallpaper.sh &
sh $HOME/.scripts/zeroautolock.sh &
xsetroot -name "`date +%a` `date +%D`" &
sleep 1 ;
exec dwm

