settings:
  keyb_path: /home/gabrielzschmitz/.config/keyb/keyb.yml
  debug: false
  reverse: true
  mouse: true
  title: ""
  prompt: 'keyb > '
  placeholder: '...'
  prefix_sep: ;
  sep_width: 4
  margin: 0
  padding: 1
  border: hidden
color:
  prompt: "6"
  cursor_fg: "7"
  cursor_bg: ""
  filter_fg: "6"
  filter_bg: ""
  counter_fg: "4"
  counter_bg: ""
  placeholder_fg: "4"
  placeholder_bg: ""
  border_color: "6"

